export const SELECT_ALL_PRODUCTS = 'SELECT_ALL_PRODUCTS';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';

export const SELECT_PASTORDER = 'SELECT_PASTORDER';
export const SELECT_ALL_REVIEWS = 'SELECT_ALL_REVIEWS';
