export const SELECT_ALL_PRODUCTS = 'SELECT_ALL_PRODUCTS';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
